export const TYPES = {
  ADD_TO_FAV_NAV: "ADD_TO_FAV_NAV",
  READ_STATES: "READ_STATE",
  ADD_TO_FAV: "ADD_TO_FAV",
  REMOVE_ONE_FAV: "REMOVE_ONE_FAV",
  REMOVE_ALL_FAVS: "REMOVE_ALL_FAVS",
  CLEAR_FAVS: "CLEAR_FAVS",
};
